add_newline = true

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[directory]
truncation_length = 4
prefix = "📂 "

[git_branch]
symbol = "🌱 "

[package]
symbol = "🎁 "

[time]
disabled = false
format = "🕙 %T"
