add_newline = true
command_timeout = 500

[character]
error_symbol = "[❯](bold red)"
format = "$symbol "
success_symbol = "[❯](bold green)"

[directory]
format = "📂 [$path]($style) "
truncation_length = 4

[git_branch]
symbol = "🌱 "

[package]
symbol = "🎁 "

[time]
disabled = false
format = "🕙 $time"
